[shell]
program = "/usr/bin/fish"

[colors.bright]
black = "0x665c54"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "0xebdbb2"
text = "0x1d2021"

[colors.normal]
black = "0x1d2021"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[font]
size = 10

[font.normal]
family = "JetBrainsMono+NerdFont"
style = "Regular"

[font.bold]
family = "JetBrainsMono+NerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono+NerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono+NerdFont"
style = "Italic"

