#!/bin/dash

wlr-randr --output DP-1 --mode 2560x1440@165.080002Hz

# swayidle -w timeout 600 'wlr-randr --output DP-1 --off' \
#             resume 'wlr-randr --output DP-1 --on' \
#             before-sleep 'swaylock -f --image $HOME/config/wallpaper.jpg'

for pointer in $(riverctl list-inputs | grep "pointer")
do
  riverctl input $pointer accel-profile flat
  riverctl input $pointer pointer-accel 0
done

/bin/dash $HOME/config/scripts/launch-waybar &
swaybg -i $HOME/config/wallpaper.jpg -m fill &
nm-applet --indicator &
blueman-applet &
discord --start-minimized &
